require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe XactionsController do

  # This should return the minimal set of attributes required to create a valid
  # Xaction. As you add validations to Xaction, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # XactionsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all xactions as @xactions" do
      xaction = Xaction.create! valid_attributes
      get :index, {}, valid_session
      assigns(:xactions).should eq([xaction])
    end
  end

  describe "GET show" do
    it "assigns the requested xaction as @xaction" do
      xaction = Xaction.create! valid_attributes
      get :show, {:id => xaction.to_param}, valid_session
      assigns(:xaction).should eq(xaction)
    end
  end

  describe "GET new" do
    it "assigns a new xaction as @xaction" do
      get :new, {}, valid_session
      assigns(:xaction).should be_a_new(Xaction)
    end
  end

  describe "GET edit" do
    it "assigns the requested xaction as @xaction" do
      xaction = Xaction.create! valid_attributes
      get :edit, {:id => xaction.to_param}, valid_session
      assigns(:xaction).should eq(xaction)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Xaction" do
        expect {
          post :create, {:xaction => valid_attributes}, valid_session
        }.to change(Xaction, :count).by(1)
      end

      it "assigns a newly created xaction as @xaction" do
        post :create, {:xaction => valid_attributes}, valid_session
        assigns(:xaction).should be_a(Xaction)
        assigns(:xaction).should be_persisted
      end

      it "redirects to the created xaction" do
        post :create, {:xaction => valid_attributes}, valid_session
        response.should redirect_to(Xaction.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved xaction as @xaction" do
        # Trigger the behavior that occurs when invalid params are submitted
        Xaction.any_instance.stub(:save).and_return(false)
        post :create, {:xaction => {}}, valid_session
        assigns(:xaction).should be_a_new(Xaction)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Xaction.any_instance.stub(:save).and_return(false)
        post :create, {:xaction => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested xaction" do
        xaction = Xaction.create! valid_attributes
        # Assuming there are no other xactions in the database, this
        # specifies that the Xaction created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Xaction.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => xaction.to_param, :xaction => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested xaction as @xaction" do
        xaction = Xaction.create! valid_attributes
        put :update, {:id => xaction.to_param, :xaction => valid_attributes}, valid_session
        assigns(:xaction).should eq(xaction)
      end

      it "redirects to the xaction" do
        xaction = Xaction.create! valid_attributes
        put :update, {:id => xaction.to_param, :xaction => valid_attributes}, valid_session
        response.should redirect_to(xaction)
      end
    end

    describe "with invalid params" do
      it "assigns the xaction as @xaction" do
        xaction = Xaction.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Xaction.any_instance.stub(:save).and_return(false)
        put :update, {:id => xaction.to_param, :xaction => {}}, valid_session
        assigns(:xaction).should eq(xaction)
      end

      it "re-renders the 'edit' template" do
        xaction = Xaction.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Xaction.any_instance.stub(:save).and_return(false)
        put :update, {:id => xaction.to_param, :xaction => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested xaction" do
      xaction = Xaction.create! valid_attributes
      expect {
        delete :destroy, {:id => xaction.to_param}, valid_session
      }.to change(Xaction, :count).by(-1)
    end

    it "redirects to the xactions list" do
      xaction = Xaction.create! valid_attributes
      delete :destroy, {:id => xaction.to_param}, valid_session
      response.should redirect_to(xactions_url)
    end
  end

end
